#########################################
# Copyright (C) 2016 Project Bonfire    #
#                                       #
# This file is automatically generated! #
#             DO NOT EDIT!              #
#########################################

vlib work

# Include files and compile them

# packages
vcom "network_files/component_pack.vhd"
vcom "plasma_RTL/mlite_pack.vhd"
vcom "../../../Test/credit_based/TB_Package_32_bit_credit_based_NI.vhd"

# router and NI components
vcom "network_files/Allocator_with_checkers_with_FI/Arbiter_in_one_hot_checkers.vhd"
vcom "network_files/Allocator_with_checkers_with_FI/Arbiter_out_one_hot_pseudo_checkers.vhd"
vcom "network_files/Allocator_with_checkers_with_FI/allocator_logic_pseudo_checkers.vhd"
vcom "network_files/Allocator_with_checkers_with_FI/allocator_credit_counter_logic_pseudo_checkers.vhd"
vcom "network_files/FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI/FIFO_one_hot_credit_based_packet_drop_classifier_support_checkers.vhd"
vcom "network_files/LBDR_packet_drop_with_checkers_with_FI/Cx_Reconf_pseudo_checkers.vhd"
vcom "network_files/LBDR_packet_drop_with_checkers_with_FI/Rxy_Reconf_pseudo_checkers.vhd"
vcom "network_files/LBDR_packet_drop_with_checkers_with_FI/LBDR_packet_drop_routing_part_pseudo_checkers.vhd"

vcom -cover bcesfx "network_files/Allocator_with_checkers_with_FI/Arbiter_in_one_hot_with_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/Allocator_with_checkers_with_FI/arbiter_out_one_hot_with_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/Allocator_with_checkers_with_FI/allocator_with_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI/FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/LBDR_packet_drop_with_checkers_with_FI/LBDR_packet_drop_with_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/ParityChecker_for_LBDR.vhd"
vcom -cover bcesfx "network_files/counter_threshold.vhd"
vcom -cover bcesfx "network_files/Fault_injector.vhd"
vcom "network_files/shift_register_serial_in.vhd"
vcom -cover bcesfx "network_files/NI.vhd"
vcom -cover bcesfx "network_files/xbar.vhd"

vcom -cover bcesfx "network_files/customized_routers/Router_32_bit_NW_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/customized_routers/Router_32_bit_NE_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/customized_routers/Router_32_bit_SW_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"
vcom -cover bcesfx "network_files/customized_routers/Router_32_bit_SE_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"

# IJTAG-related components
vcom "IJTAG_files/SIB_mux_pre_FCX_SELgate.vhd"
vcom "IJTAG_files/ScanMux.vhd"
vcom "IJTAG_files/ScanRegister.vhd"
vcom "IJTAG_files/SReg.vhd"
vcom "IJTAG_files/AsyncDataRegisterAdapter.vhd"
vcom "network_files/network_2x2_customized_packet_drop_SHMU_credit_based_with_checkers.vhd"
 
vcom "Testbenches/NI_Test/network_2x2_NI_Test_packet_drop_Rand_SHMU_credit_based_with_checkers_tb.vhd"


# Start the simulation
vsim -coverage -voptargs="+cover=bcestfx" work.tb_network_2x2

# Draw waves
do do_files/wave_2x2.do
# Run the simulation for 15000ns
do do_files/fault_inject_links.do 	#use to inject files in the simulation(not using IJTAG)
coverage report -file NoC_coverage_report.txt -byfile -assert -directive -cvg -codeAll