#########################################
# Copyright (C) 2016 Project Bonfire    #
#                                       #
# This file is automatically generated! #
#             DO NOT EDIT!              #
#########################################

vlib work

# Include files and compile them
vcom "mlite_pack.vhd"
vcom "flit_tracker.vhd"
vcom "/Allocator_with_checkers_with_FI/Arbiter_in_one_hot_checkers.vhd"
vcom "/Allocator_with_checkers_with_FI/Arbiter_in_one_hot_with_checkers.vhd"
vcom "/Allocator_with_checkers_with_FI/Arbiter_out_one_hot_pseudo_checkers.vhd"
vcom "/Allocator_with_checkers_with_FI/arbiter_out_one_hot_with_checkers.vhd"
vcom "/Allocator_with_checkers_with_FI/allocator_credit_counter_logic_pseudo_checkers.vhd"
vcom "/Allocator_with_checkers_with_FI/allocator_logic_pseudo_checkers.vhd"
vcom "/Allocator_with_checkers_with_FI/allocator_with_checkers.vhd"
vcom "counter_threshold.vhd"
vcom "checkers_counter_threshold.vhd"
vcom "/FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI/FIFO_one_hot_credit_based_packet_drop_classifier_support_checkers.vhd"
vcom "/FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI/FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers.vhd"
vcom "/LBDR_packet_drop_with_checkers_with_FI/Cx_Reconf_pseudo_checkers.vhd"
vcom "/LBDR_packet_drop_with_checkers_with_FI/Rxy_Reconf_pseudo_checkers.vhd"
vcom "/LBDR_packet_drop_with_checkers_with_FI/LBDR_packet_drop_routing_part_pseudo_checkers.vhd"
vcom "/LBDR_packet_drop_with_checkers_with_FI/LBDR_packet_drop_with_checkers.vhd"
vcom "NI.vhd"
vcom "xbar.vhd"
vcom "Router_32_bit_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers.vhd"
vcom "TB_Package_32_bit_credit_based_NI.vhd"
vcom "network_2x2_packet_drop_SHMU_credit_based.vhd"
vcom "network_2x2_NI_Test_packet_drop_Rand_SHMU_credit_based_tb.vhd"

# Start the simulation
vsim work.tb_network_2x2

# Draw waves
do wave_2x2.do
# Run the simulation
# run 11000 ns
do fault_inject.do
