#########################################
# Copyright (C) 2016 Project Bonfire    #
#                                       #
# This file is automatically generated! #
#             DO NOT EDIT!              #
#########################################

vlib work

# Include files and compile them


vcom -cover bcesfx "component_pack.vhd"
vcom -cover bcesfx "plasma_RTL/mlite_pack.vhd"
vcom -cover bcesfx "Allocator_with_checkers_with_FI/Arbiter_in_one_hot_checkers.vhd"
vcom -cover bcesfx "Allocator_with_checkers_with_FI/Arbiter_in_one_hot_with_checkers_with_FI.vhd"
vcom -cover bcesfx "Allocator_with_checkers_with_FI/Arbiter_out_one_hot_pseudo_checkers.vhd"
vcom -cover bcesfx "Allocator_with_checkers_with_FI/arbiter_out_one_hot_with_checkers_with_FI.vhd"
vcom -cover bcesfx "Allocator_with_checkers_with_FI/allocator_logic_pseudo_checkers.vhd"
vcom -cover bcesfx "Allocator_with_checkers_with_FI/allocator_credit_counter_logic_pseudo_checkers.vhd"
vcom -cover bcesfx "Allocator_with_checkers_with_FI/allocator_with_checkers_with_FI.vhd"
vcom -cover bcesfx "FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI/FIFO_one_hot_credit_based_packet_drop_classifier_support_checkers.vhd"
vcom -cover bcesfx "FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI/FIFO_one_hot_credit_based_packet_drop_classifier_support_with_checkers_with_FI.vhd"
vcom -cover bcesfx "LBDR_packet_drop_with_checkers_with_FI/Cx_Reconf_pseudo_checkers.vhd"
vcom -cover bcesfx "LBDR_packet_drop_with_checkers_with_FI/Rxy_Reconf_pseudo_checkers.vhd"
vcom -cover bcesfx "LBDR_packet_drop_with_checkers_with_FI/LBDR_packet_drop_routing_part_pseudo_checkers.vhd"
vcom -cover bcesfx "LBDR_packet_drop_with_checkers_with_FI/LBDR_packet_drop_with_checkers_with_FI.vhd"
vcom -cover bcesfx "ParityChecker_for_LBDR.vhd"
vcom -cover bcesfx "counter_threshold.vhd"
vcom -cover bcesfx "checkers_counter_threshold.vhd"
vcom -cover bcesfx "Fault_injector.vhd"
vcom -cover bcesfx "shift_register_serial_in.vhd"
vcom -cover bcesfx "NI.vhd"
vcom -cover bcesfx "xbar.vhd"

# IJTAG-related components
vcom -cover bcesfx "SIB_mux_pre_FCX_SELgate.vhd"
vcom -cover bcesfx "ScanMux.vhd"
vcom -cover bcesfx "ScanRegister.vhd"

vcom -cover bcesfx "plasma_RTL/alu.vhd"
vcom -cover bcesfx "plasma_RTL/bus_mux.vhd"
vcom -cover bcesfx "plasma_RTL/cache.vhd"
vcom -cover bcesfx "plasma_RTL/control.vhd"
vcom -cover bcesfx "plasma_RTL/ddr_ctrl.vhd"
vcom -cover bcesfx "plasma_RTL/eth_dma.vhd"
vcom -cover bcesfx "plasma_RTL/mem_ctrl.vhd"
vcom -cover bcesfx "plasma_RTL/mult.vhd"
vcom -cover bcesfx "plasma_RTL/pc_next.vhd"
vcom -cover bcesfx "plasma_RTL/pipeline.vhd"
vcom -cover bcesfx "plasma_RTL/ram.vhd"
vcom -cover bcesfx "plasma_RTL/reg_bank.vhd"
vcom -cover bcesfx "plasma_RTL/shifter.vhd"
vcom -cover bcesfx "plasma_RTL/uart.vhd"
vcom -cover bcesfx "plasma_RTL/mlite_cpu.vhd"
vcom -cover bcesfx "plasma_RTL/plasma.vhd"

vcom -cover bcesfx "NoC_Node.vhd"

vcom -cover bcesfx "customized_routers/Router_32_bit_NW_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"
vcom -cover bcesfx "customized_routers/Router_32_bit_NE_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"
vcom -cover bcesfx "customized_routers/Router_32_bit_SW_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"
vcom -cover bcesfx "customized_routers/Router_32_bit_SE_credit_based_packet_drop_classifier_SHMU_will_full_set_of_checkers_with_FI.vhd"

vcom -cover bcesfx "network_2x2_customized_packet_drop_SHMU_credit_based_with_checkers.vhd"
# vcom -cover bcesfx "temporary/network_2x2_customized_packet_drop_SHMU_credit_based_with_checkers_with_PE_top.vhd"

vcom -cover bcesfx "network_2x2_NI_PE_credit_based_tb.vhd"
# vcom -cover bcesfx "temporary/network_2x2_NI_PE_credit_based_tb_temp.vhd"

# Start the simulation
vsim -coverage -voptargs="+cover=bcestfx" work.tb_network_2x2

# Draw waves
do wave_2x2.do
# Run the simulation
# do fault_inject.do 	#use to inject files in the simulation(not using IJTAG)
run 12000 ns
