#########################################
# Copyright (C) 2016 Project Bonfire    #
#                                       #
# This file is automatically generated! #
#             DO NOT EDIT!              #
#########################################

vlib work

# Include files and compile them

# packages
vcom -cover bcesfx "network_files/component_pack.vhd"
vcom -cover bcesfx "plasma_RTL/mlite_pack.vhd"


vlog -reportprogress 300 -work work "plasma_RTL/ts1n40lpb1024x32m4s_210b_tt1p1v25c.v"
vcom -cover bcesfx "plasma_RTL/ram_wrapper.vhd"


vcom -cover bcesfx "Testbenches/mem_wrap_tb.vhd"

# Start the simulation
vsim -coverage -voptargs="+cover=bcestfx" work.mem_wrap_tb
add wave -position insertpoint sim/:mem_wrap_tb:ram_unit:RAM_unit:MEMORY
add wave -position insertpoint sim/:mem_wrap_tb:ram_unit:RAM_unit:Q
add wave -position insertpoint sim/:mem_wrap_tb:address
add wave -position insertpoint sim/:mem_wrap_tb:clk
run 400ns